name: video_to_audio_converter
description: "Extract Audio from Videos. Merge multiple Audio Files. Change the Format of Files. Set Audio as Ringtones"
publish_to: 'none'

version: 1.0.3+6
environment:

  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  get: ^4.7.2
  # Audio & Video video_player: ^2.10.0 video_thumbnail: ^0.5.6
  just_audio: ^0.10.5
  file_picker: ^10.3.3
  video_player: ^2.10.0
#  device_preview: ^1.3.1

  video_thumbnail: ^0.5.6
  ffmpeg_kit_flutter_new: ^3.2.0

  # Device / System info
  path_provider: ^2.1.5
  path: ^1.9.1
  device_info_plus: ^12.1.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  # Utilities
  fluttertoast: ^9.0.0
  share_plus: ^12.0.0
  audio_waveforms: ^1.3.0
  ringtone_set_mul:
    path: ./plugins/ringtone_set_mul
  # Network / API
  dio: ^5.9.0
  http: ^0.13.6
  http_parser: ^4.1.2
  flutter_downloader: ^1.12.0
  # Ads
  google_mobile_ads: ^5.3.1

  # UI Effects
  shimmer: ^3.0.0

  # Permissions
  permission_handler: ^12.0.1
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  android: true
  ios: true
  web: true

  # Background color
  color: "#FFFFFF"

  # Main splash image (for Android <12, iOS, Web)
  image: "assets/images/logo.png"

  # iOS + Web alignment
  ios_content_mode: scaleAspectFit
  web_image_mode: center

  # Android 12 specific configuration
  android_12:
    image: "assets/images/logo.png"
    color: "#FFFFFF"


